/** Helpers compartilhados pelos testes de frontend. */

import { vi } from "vitest";

import type {
  BacktestJobStatus,
  BacktestOptions,
  BacktestRunDetail,
  BacktestRunSummary,
  BacktestSignal,
  SignalPage,
} from "@/types/backtest";
import type { DashboardSummary, SignalReport, SystemStatus } from "@/types/api";

/**
 * Substitui `global.fetch` por uma implementacao controlada pelo teste.
 *
 * Devolve o mock e um helper para inspecionar as chamadas. Nenhum teste
 * toca a rede.
 */
export function mockFetch(
  handler: (url: string, init?: RequestInit) => Response | Promise<Response>,
) {
  const calls: { url: string; init?: RequestInit }[] = [];
  const fn = vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
    const url = typeof input === "string" ? input : String(input);
    calls.push({ url, init });
    return handler(url, init);
  });
  vi.stubGlobal("fetch", fn);
  return { fn, calls };
}

/** Resposta JSON com status configuravel. */
export function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

/* --------------------------------------------------------------- fixtures */

export const systemStatus: SystemStatus = {
  status: "ok",
  version: "1.1.0",
  python_version: "3.11.9",
  generated_at: "2025-05-05 16:00:00",
  computed_in_ms: 80,
  has_snapshot: true,
  n_signals: 167,
  n_games: 15,
  data_source: "Dataset local sintetico (seed fixo)",
  providers: { "The Odds API": false },
  message: null,
};

export const dashboardSummary: DashboardSummary = {
  generated_at: "2025-05-05 16:00:00",
  computed_in_ms: 80,
  configuration: {
    bankroll: 1000,
    kelly_fraction: 0.25,
    min_ev: 0.02,
    stake_cap: 0.01,
    max_exposure: 0.25,
    use_xg: true,
    rounds: 3,
  },
  kpis: {
    total: 2,
    strong: 1,
    medium: 1,
    weak: 0,
    strong_pct: 0.5,
    medium_pct: 0.5,
    weak_pct: 0,
    expected_profit: 11.63,
    expected_profit_pct: 0.0116,
    avg_stake_pct: 0.01,
    total_exposure: 250,
    total_exposure_pct: 0.25,
    worst_case_loss: 250,
    gross_profit_if_all_win: 300,
    exposure_scaled_by: 0.186,
    max_ev: 0.117,
  },
  n_games: 15,
  n_teams: 20,
  n_bookmakers: 10,
  n_markets: 8,
  data_source: "Dataset local sintetico (seed fixo)",
};

export const betDecisionNoBet = {
  action: "NO_BET" as const,
  reason: "falhou: evidencia_confiavel",
  fraction: 0,
  conservative_roi: 0.0071,
  kelly_full: 0.0762,
  checks: [
    {
      name: "evidencia_confiavel",
      passed: false,
      detail:
        "status 'exploratory': odds sem timestamp/validacao nao sustentam dinheiro real",
    },
    {
      name: "limite_inferior_positivo",
      passed: true,
      detail: "ROI conservador +0,71%",
    },
    {
      name: "amostra_suficiente",
      passed: true,
      detail: "6748 apostas (minimo 1000)",
    },
    {
      name: "ruina_toleravel",
      passed: true,
      detail: "P(cair a metade) 0,78%",
    },
  ],
};

export const signalReport: SignalReport = {
  generated_at: "2025-05-05T16:00:00Z",
  bankroll: 1000,
  kpis: dashboardSummary.kpis,
  source: "real",
  source_detail: "Jogos futuros reais com odds reais (football-data.co.uk).",
  skipped_no_rating: 18,
  skipped_insufficient_books: 0,
  decision: betDecisionNoBet,
  calibration: {
    measured_on: "13.334 partidas (top-5 europeu, 2018-2025)",
    ev_predicted: 0.224,
    return_realized: -0.017,
    gap_pp: 0.241,
    simulated_roi: -0.055,
    verdict: "O modelo e sistematicamente superconfiante.",
  },
  signals: [
    {
      id: "0|A vs B|Handicap Asiatico|AH Casa +1",
      match: "Botafogo vs Sao Paulo",
      home: "Botafogo",
      away: "Sao Paulo",
      kickoff: "2025-05-10",
      league: "Serie A",
      round_label: "Rodada 21",
      market: "Handicap Asiatico",
      outcome: "AH Casa +1",
      best_odd: 1.22,
      best_book: "Pinnacle",
      median_odd: 1.2,
      fair_odd: 7.19,
      n_books: 10,
      model_prob: 0.916,
      market_prob: 0.139,
      edge: 0.776,
      ev: 0.117,
      kelly: 0.496,
      stake: 10,
      stake_pct: 0.01,
      expected_profit: 1.17,
      expected_profit_pct: 0.0012,
      gross_profit_if_win: 2.2,
      loss_if_lose: 10,
      confidence: "FORTE",
      rationale: "modelo ve 77.6pp acima do mercado",
    },
    {
      id: "1|C vs D|Resultado Final (1X2)|X",
      match: "Cruzeiro vs Botafogo",
      home: "Cruzeiro",
      away: "Botafogo",
      kickoff: "2025-05-11",
      league: "Serie A",
      round_label: "Rodada 21",
      market: "Resultado Final (1X2)",
      outcome: "X",
      best_odd: 4.02,
      best_book: "Betfair",
      median_odd: 3.9,
      fair_odd: 3.86,
      n_books: 10,
      model_prob: 0.277,
      market_prob: 0.259,
      edge: 0.018,
      ev: 0.114,
      kelly: 0.05,
      stake: 10,
      stake_pct: 0.01,
      expected_profit: 1.14,
      expected_profit_pct: 0.0011,
      gross_profit_if_win: 30.2,
      loss_if_lose: 10,
      confidence: "MEDIA",
      rationale: "edge dentro da margem de erro",
    },
  ],
  top_tips: ["1. [FORTE] Botafogo vs Sao Paulo"],
};

export const backtestOptions: BacktestOptions = {
  min_date: "2025-01-26",
  max_date: "2025-12-14",
  competitions: ["Serie A"],
  markets: [
    { key: "1x2", label: "Resultado Final (1X2)" },
    { key: "ou", label: "Total de Gols" },
  ],
  default_config: {
    start_date: null,
    end_date: null,
    competitions: [],
    market_keys: ["1x2", "ou"],
    bankroll: 1000,
    kelly_fraction: 0.25,
    stake_cap: 0.01,
    min_ev: 0.02,
    max_exposure: 0.25,
    use_xg: true,
    min_confidence: "FRACA",
    min_history: 100,
    odds_source: "naive_synthetic",
    apply_exposure_cap: true,
    corpus_source: "local",
    odds_sport_key: "soccer_brazil_campeonato",
    odds_closing: true,
    odds_books: [],
  },
  min_history_default: 100,
  odds_sources: [
    { key: "naive_synthetic", label: "Mercado ingênuo sintético", available: true, note: "baseline" },
    { key: "football_data_uk", label: "Odds reais — football-data.co.uk", available: true, note: "odds reais" },
    { key: "real_historical", label: "Odds históricas reais", available: false, note: "requer chave" },
  ],
  scanner_ev_thresholds: { forte: 0.08, media: 0.045, fraca: 0.02 },
  min_sample: 30,
  point_in_time_schema: "pit-1",
  model_version: "1.1.0",
  missing_data_notes: [
    {
      dado: "odds historicas reais",
      por_que: "sem elas o edge e medido contra um baseline",
      quem_fornece: "The Odds API",
      como_plugar: "BETGSN_ODDS_API_KEY",
    },
  ],
  books: ["Pinnacle", "Bet365", "Betfair Exchange"],
  corpora: [
    {
      key: "local",
      label: "Dataset local (sintético)",
      available: true,
      n_matches: 380,
      first_kickoff: "2025-01-26",
      last_kickoff: "2025-12-14",
      competitions: ["Serie A"],
      fingerprint: "abc123",
      note: "",
    },
    {
      key: "imported",
      label: "Temporadas reais importadas",
      available: false,
      n_matches: 0,
      first_kickoff: null,
      last_kickoff: null,
      competitions: [],
      fingerprint: null,
      note: "Nada importado.",
    },
    {
      key: "football_data_uk",
      label: "Ligas europeias (football-data.co.uk)",
      available: true,
      n_matches: 104177,
      first_kickoff: "2000-08-19",
      last_kickoff: "2026-05-24",
      competitions: ["Premier League (England)", "La Liga (Spain)"],
      fingerprint: "fduk123",
      note: "COM odds reais.",
    },
  ],
  odds_cache: [],
};

export const backtestJobStatus: BacktestJobStatus = {
  job_id: "btjob_1",
  phase: "analyzing",
  done: 50,
  total: 100,
  progress: 0.5,
  message: "Analisando partidas (50/100)",
  run_id: null,
  error: null,
};

export function makeSignal(overrides: Partial<BacktestSignal> = {}): BacktestSignal {
  return {
    signal_id: "sig1",
    match_id: "2025-04-06T16:00:00Z|Criciuma|Flamengo",
    competition: "Serie A",
    season: "2025",
    kickoff: "2025-04-06 16:00",
    kickoff_utc: "2025-04-06T16:00:00Z",
    home: "Criciuma",
    away: "Flamengo",
    market: "Handicap Asiatico",
    outcome: "AH Fora -1",
    best_odd: 5.2,
    best_book: "Pinnacle",
    median_odd: 5.0,
    fair_odd: 32.14,
    n_books: 10,
    model_prob: 0.593,
    market_prob: 0.031,
    edge: 0.562,
    ev: 2.083,
    kelly: 0.496,
    stake: 10,
    stake_pct: 0.01,
    expected_profit: 20.83,
    confidence: "FORTE",
    rationale: "modelo ve 56.2pp acima do mercado",
    lambda_home: 0.959,
    lambda_away: 2.372,
    home_attack: 0.747,
    home_defense: 1.14,
    away_attack: 1.389,
    away_defense: 0.775,
    home_xg_for: 1.02,
    away_xg_for: 2.11,
    n_prior_matches: 100,
    league_goals: 3.14,
    attack_blend: 0.5,
    odds_source: "naive_synthetic",
    odds_as_of: "2025-04-06T16:00:00Z",
    model_version: "1.1.0",
    config_hash: "5fdb21ca0d87014d",
    result_home_goals: 1,
    result_away_goals: 4,
    outcome_result: "win",
    settled: true,
    realized_return: 4.2,
    profit: 42,
    ...overrides,
  };
}

export const signalPage: SignalPage = {
  total: 1,
  offset: 0,
  limit: 50,
  items: [makeSignal()],
};

export const backtestRunSummary: BacktestRunSummary = {
  run_id: "bt_20250919_120000_abc12345",
  created_at: "2025-09-19 12:00:00",
  config_hash: "abc12345",
  model_version: "1.1.0",
  n_signals: 6177,
  n_matches_evaluated: 280,
  n_matches_skipped: 100,
  duration_ms: 3435,
  hit_rate: 0.5258,
  brier: 0.2167,
  return_pct: 1.131,
  max_drawdown: 0.0847,
};

export const backtestRunDetail: BacktestRunDetail = {
  run_id: "bt_20250919_120000_abc12345",
  created_at: "2025-09-19 12:00:00",
  config_hash: "abc12345",
  model_version: "1.1.0",
  point_in_time_schema: "pit-1",
  config: backtestOptions.default_config,
  aggregate: {
    n_signals: 6177,
    n_settled: 6090,
    n_unsettled: 0,
    n_wins: 3202,
    n_losses: 2888,
    n_pushes: 87,
    hit_rate: 0.5258,
    hit_rate_ci: [0.5132, 0.5383],
    avg_odd: 2.514,
    avg_model_prob: 0.564,
    avg_market_prob: 0.368,
    avg_edge: 0.196,
    avg_ev: 0.1962,
    avg_realized_return: 0.1113,
    realized_return_ci: [0.09, 0.13],
    brier: 0.2167,
    brier_ci: [0.213, 0.22],
    logloss: 0.6225,
    ev_gap: 0.0849,
    sample_sufficient: true,
  },
  calibration: [
    {
      label: "50–55%",
      lower: 0.5,
      upper: 0.55,
      n: 583,
      avg_predicted: 0.526,
      observed_rate: 0.499,
      ci_low: 0.459,
      ci_high: 0.54,
      sufficient: true,
    },
    {
      label: "55–60%",
      lower: 0.55,
      upper: 0.6,
      n: 544,
      avg_predicted: 0.574,
      observed_rate: 0.515,
      ci_low: 0.473,
      ci_high: 0.556,
      sufficient: true,
    },
  ],
  ev_buckets: [
    {
      label: "2–5%",
      lower: 0.02,
      upper: 0.05,
      n: 1113,
      avg_ev: 0.035,
      observed_rate: 0.566,
      avg_realized_return: 0.011,
      ci_low: 0.537,
      ci_high: 0.595,
      sufficient: true,
    },
    {
      label: "15%+",
      lower: 0.15,
      upper: 1,
      n: 2540,
      avg_ev: 0.364,
      observed_rate: 0.482,
      avg_realized_return: 0.241,
      ci_low: 0.462,
      ci_high: 0.502,
      sufficient: true,
    },
  ],
  temporal: {
    day: [{ label: "2025-04-06", n: 30, hit_rate: 0.53, avg_ev: 0.19, realized_return: 0.12, profit: 36, bankroll_end: 1036 }],
    week: [{ label: "2025-W14", n: 200, hit_rate: 0.52, avg_ev: 0.19, realized_return: 0.11, profit: 220, bankroll_end: 1220 }],
    month: [{ label: "2025-04", n: 907, hit_rate: 0.539, avg_ev: 0.19, realized_return: 0.137, profit: 139.75, bankroll_end: 1139.75 }],
  },
  segments: [
    {
      dimension: "mercado",
      segment: "Escanteios",
      n: 1528,
      observed_rate: 0.508,
      avg_predicted: 0.549,
      avg_ev: 0.2,
      brier: 0.2479,
      ci_low: 0.483,
      ci_high: 0.533,
      sufficient: true,
    },
  ],
  simulation: {
    initial_bankroll: 1000,
    final_bankroll: 2130.96,
    profit: 1130.96,
    return_pct: 1.131,
    total_staked: 10261,
    roi: 0.1102,
    max_drawdown: 0.0847,
    max_drawdown_day: "2025-10-12",
    longest_win_streak: 12,
    longest_loss_streak: 25,
    n_bets: 6175,
    n_wins: 3202,
    n_losses: 2888,
    n_pushes: 85,
    return_std: 1.98,
    equity: [
      { day: "2025-04-06", bankroll: 1036, peak: 1036, drawdown: 0, staked: 200, profit: 36, n_signals: 30 },
      { day: "2025-04-13", bankroll: 1100, peak: 1100, drawdown: 0, staked: 210, profit: 64, n_signals: 32 },
    ],
    exposure_scaled_days: 28,
  },
  meta: {
    started_at: "2025-09-19 12:00:00",
    finished_at: "2025-09-19 12:00:03",
    n_matches_in_period: 380,
    skipped_reasons: { historico_insuficiente: 100 },
    duration_ms: 3435,
  },
  missing_data_notes: backtestOptions.missing_data_notes,
};
